### ISSUE TITLE
Link on /community/ page to 'mailing list' results in error... 

### ISSUE THREAD

**Issue by tallship** [opencontainers/web#14]
The link at https://www.opencontainers.org/community to the first (dev) mailing list is broken:
https://groups.google.com/a/opencontainers.org/forum/#!forum/dev%E2%80%8B is the actual link, but it should be:
 https://groups.google.com/a/opencontainers.org/forum/#!forum/dev 

This results in a, "The group name is invalid.", error at Google.

**Comment by caniszczyk** [comment]
Fixed now, thanks for the bug report :)
