### ISSUE TITLE
https://www.opencontainers.org/about has a "in 2-3 weeks" release target

### ISSUE THREAD

**Issue by wking** [opencontainers/web#18]
This is _really_ stale ;).  Or maybe the release is always close, but never quite here :p.

**Comment by wking** [comment]
Ah, actually that is the _draft_ release target, and with a few v0.x releases for the runtime-spec, that target has probably already been met.

**Comment by caniszczyk** [comment]
I cleaned up the page so the reference is gone, the page was definitely outdated :)
