### ISSUE TITLE
Missmatch between charter's initial maintainer list and runC's maintainer list(s)

### ISSUE THREAD

**Issue by wking** [opencontainers/web#5]
In #4, I'm proposing we explicitly support per-project TDCs, but the current charter seems to read like it expects a single, OCI-wide TDC.  If #4 doesn't land (or until it lands?), it would be nice to have that TDC be internally consistent.  The [current charter](https://github.com/opencontainers/web/blob/33bc0b2597cbfd37e4728660d4b74272603b6f97/content/charter.md) reads (§4.e):

> The initial leadership of the TDC shall be Michael Crosby (chief maintainer, Docker, @crosbymichael), Rohit Jnagal (google,@rgnagal), Victor Marmol (google, @vmarmol), Mrunal Patel (redhat, @mrunalp), Alexandr Morozov (docker, @LK4D4), Daniel Minh (@dqminh), Tianon Gravi (@tianon), Vincent Batts (redhat, @vbatts), Brandon Philipps (CoreOS, @philips)

The [recent press release](https://github.com/opencontainers/web/blob/33bc0b2597cbfd37e4728660d4b74272603b6f97/content/pressrelease-july-2015.md) has:

> A [draft charter](https://www.opencontainers.org/charter/) for OCI is available now and the maintainers are sharing the project’s day-to-day technical governance in a [Maintainer’s Guide](https://github.com/opencontainers/runc/blob/master/MAINTAINERS_GUIDE.md).

Which maps the [charter's](https://github.com/opencontainers/web/blob/33bc0b2597cbfd37e4728660d4b74272603b6f97/content/charter.md) “governance guidelines” (§4.b.viii)  to that maintainer guide.  So I expect the current runC [`MAINTAINERS`](https://github.com/opencontainers/runc/blob/9be9157fc5cd9cf59c155fe194a0acc5f1e6f926/MAINTAINERS) file lists all TDC members.  Howeverv, that file only lists @crosbymichael, @rjnagal, @vmarmol, @mrunalp, @LK4D4, and @dqminh, not @tianon, @vbatts, or @philips.

One possible explanation for the difference is that the maintainer file at some point contained the set listed in the charter, but that the three missing developers have since left the TDC.  Looking through the history of the maintainers file:
- @creack was there from the initial opencontainers/runc@6415e8b (2014-02-18) until opencontainers/runc@10597cb9 (2014-06-10)
- @tianon was there from opencontaines/runc@e9f44b52d (2014-08-04) until opencontainers/runc@f637539d (2015-06-26)

I don't see @vbatts or @philips in any version of the file.

Poking around some more, I see [two](https://github.com/opencontainers/runc/blob/9be9157fc5cd9cf59c155fe194a0acc5f1e6f926/libcontainer/netlink/MAINTAINERS) [other](https://github.com/opencontainers/runc/blob/9be9157fc5cd9cf59c155fe194a0acc5f1e6f926/libcontainer/user/MAINTAINERS) maintainer files.  If those also contain TDC members, then that brings @creack and @tianon back into the TDC set and also adds @cyphar.

So it would be nice to add some clarity on the following questions:
1. How is runC listing TDC members?  See my [`GOVERNANCE.md` suggestion](https://github.com/opencontainers/web/pull/4#issuecomment-129032943) for one option.
2. Which maintainer listing (the one in the charter, or the one in runC) is stale?

**Comment by vbatts** [comment]
your investigations is conflating runc and OCI. Also the history of runc is that it comes from libcontainer and nsinit. There is history there that doesn't include maintainers.

**Comment by cyphar** [comment]
Maintainers != TDC Leadership. I am a maintainer of `runC`, not part of the TDC leadership. AFAIK TDC leadership is an OCI-wide thing (and is based on additional criteria outside of just being a maintainer).

**Comment by cyphar** [comment]
The root `MAINTAINERS` file lists root-level maintainers (maintainers with the authority to LGTM any patchset). This is not the same as maintainers of different packages within runc. I only maintain `libcontainer/user`, and I do not take responsibility for the merging of patches outside of that package. I'm fairly sure you'll find most of the other maintainers agree with that sentiment.

**Comment by wking** [comment]
On Tue, Aug 11, 2015 at 12:09:33AM -0700, Vincent Batts wrote:

> your investigations is conflating runc and OCI.

Right, but I explained that connection in the initial post:

> The [recent press release][2] has:
> 
> > A [draft charter](https://www.opencontainers.org/charter/) for OCI
> > is available now and the maintainers are sharing the project’s
> > day-to-day technical governance in a [Maintainer’s
> > Guide](https://github.com/opencontainers/runc/blob/master/MAINTAINERS_GUIDE.md).
> 
> Which maps the [charter's][1] “governance guidelines” (§4.b.viii) to that
> maintainer guide.
> …
> [1]: https://github.com/opencontainers/web/blob/33bc0b2597cbfd37e4728660d4b74272603b6f97/content/charter.md
> [2]: https://github.com/opencontainers/web/blob/33bc0b2597cbfd37e4728660d4b74272603b6f97/content/pressrelease-july-2015.md

Perhaps the intention is that there will eventually be a different set
of governance guidelines for the TDC, independent of the
runC-maintainer documentation?  But if so, I don't see why the press
release would bother linking to the OCI charter and runC maintainer
guide in the same breath.

I'd prefer we explicitly separate “The OCI as a whole” from the
individual projects, with per-project TDCs (#4).  But that's a
separate issue from this one (where I'm trying to understand the
connection between a single OCI-wide TDC and per-project development
rules).

**Comment by crosbymichael** [comment]
We can use one of those internet pointers `<a>` to keep things in sync

**Comment by wking** [comment]
On Tue, Aug 11, 2015 at 11:06:32AM -0700, Michael Crosby wrote:

> We can use one of those internet pointers `<a>` to keep things in
> sync

I like that, so long as the link targets don't require a §11 amendment
with a LF-Board vote to update them.  Shall I take a stab at a
pull-request doing this, or would someone with a more authoritative
understanding of the intended mapping like to handle that?

**Comment by crosbymichael** [comment]
https://github.com/opencontainers/specs/blob/master/MAINTAINERS is the source of truth for maintainers in OCI and the charter links to this file.

**Comment by wking** [comment]
On Mon, Oct 12, 2015 at 05:35:31PM -0700, Michael Crosby wrote:

> https://github.com/opencontainers/specs/blob/master/MAINTAINERS is
> the source of truth for maintainers in OCI and the charter links to
> this file.

Does it?

  $ cd ~/src/opencontainers/web
  $ git remote -v | grep origin
  origin  git://github.com/opencontainers/web.git (fetch)
  origin  git://github.com/opencontainers/web.git (push)
  $ git fetch origin
  $ git show origin/master | head -n1
  commit 33bc0b2597cbfd37e4728660d4b74272603b6f97
  $ git grep MAINTAINERS origin/master
  origin/master:content/pressrelease-july-2015.md:A [draft charter](https://www.opencontainers.org/charter/) for OCI is available now and the maintainers are sharing the project’s day-to-day technical governance in a [Maintainer’s Guide](https://github.com/opencontainers/runc/blob/master/MAINTAINERS_GUIDE.md). Maintainers have refined the specification, which is available on [GitHub](https://github.com/opencontainers/specs), and contributors can comment on specific pull requests today. A formal draft will be published for comments within the month.

So it looks like the only MAINTAINERS reference in this repository is
in a press-release, not the charter, and it's to runC's file, not the
specs'.

**Comment by wking** [comment]
The [adopted charter](https://www.opencontainers.org/governance) links to the opencontainers/specs MAINTAINERS file in §5.e, which is good.  I'm [still not clear](https://groups.google.com/a/opencontainers.org/d/msg/dev/Tjq5QJ_eez0/gLamgii3CQAJ) on the listing for the TDC contributors (as distinct from maintainers) discussed (for example) in the adopted charter's §5.b.viii.2.
